/* eslint-disable @typescript-eslint/no-explicit-any, @next/next/no-img-element */
import {notFound} from "next/navigation";
import Link from "next/link";
import {supabase} from "@/lib/supabase";
import type {ContentBlock,Project} from "@/lib/types";
export const dynamic="force-dynamic";
async function getProject(track:string,slug:string){if(!supabase)return null;const {data:view}=await supabase.from("portfolio_tracks").select("id,slug,name").eq("slug",track).eq("active",true).eq("configured",true).single();if(!view)return null;const {data}=await supabase.from("projects").select("*").eq("portfolio_track_id",view.id).eq("slug",slug).eq("status","published").is("archived_at",null).single();return data?{project:data as Project,view}:null}
export async function generateMetadata({params}:{params:Promise<{track:string;slug:string}>}){const {track,slug}=await params;const result=await getProject(track,slug);if(!result)return{};const p=result.project;return{title:`${p.title} — ${result.view.name}`,description:p.summary,openGraph:{title:p.title,description:p.summary||undefined,images:p.cover_url?[p.cover_url]:[]},twitter:{card:"summary_large_image",title:p.title,description:p.summary||undefined,images:p.cover_url?[p.cover_url]:[]}}}
export default async function ProjectPage({params}:{params:Promise<{track:string;slug:string}>}){const {track,slug}=await params;const result=await getProject(track,slug);if(!result)notFound();const project=result.project,back=`/?track=${encodeURIComponent(track)}`;return <main className="project-page"><header className="site-header"><Link className="wordmark" href={back}>PCM<span className="wordmark-dot">.</span></Link><nav><Link href={`${back}#work`}>All work</Link><Link className="nav-cta" href={`${back}#contact`}>Contact ↗</Link></nav></header><section className="project-hero"><p className="eyebrow">{project.category||"Project"}</p><h1>{project.title}</h1><p>{project.summary}</p></section>{project.cover_url&&<img className="project-cover" src={project.cover_url} alt={project.cover_alt||""}/>}<section className="project-body"><aside>{project.role&&<p><span>Role</span>{project.role}</p>}{project.organization&&<p><span>For</span>{project.organization}</p>}{project.date_label&&<p><span>Date</span>{project.date_label}</p>}{project.tags?.length>0&&<p><span>Skills</span>{project.tags.join(", ")}</p>}</aside><article>{project.description&&<p className="project-lead">{project.description}</p>}{(project.content_blocks||[]).map((b)=><Block block={b} key={b.id}/>)}{project.video_url&&<p><a href={project.video_url} target="_blank" rel="noreferrer">Watch video ↗</a></p>}{project.document_url&&<p><a href={project.document_url} target="_blank" rel="noreferrer">View document ↗</a></p>}{project.external_url&&<p><a href={project.external_url} target="_blank" rel="noreferrer">Visit project ↗</a></p>}</article></section><footer><span>Patricia Camille S. Morales</span><Link href={`${back}#work`}>More work →</Link></footer></main>}
function Block({block}:{block:ContentBlock}){const d=block.data as any;switch(block.type){case"heading":return <h2>{d.text}</h2>;case"text":return <p>{d.text}</p>;case"quote":return <blockquote>{d.text}{d.attribution&&<cite>{d.attribution}</cite>}</blockquote>;case"image":return <figure><img src={d.url} alt={d.alt||""}/>{d.caption&&<figcaption>{d.caption}</figcaption>}</figure>;case"gallery":return <div className="block-gallery">{(d.images||[]).map((im:any,i:number)=><figure key={i}><img src={im.url} alt={im.alt||""}/>{im.caption&&<figcaption>{im.caption}</figcaption>}</figure>)}</div>;case"video":return <p><a href={d.url}>Watch video ↗</a></p>;case"document":return <p><a href={d.url}>Open {d.label||"document"} ↗</a></p>;default:return null}}
