create extension if not exists pgcrypto;

create table public.site_profile (id uuid primary key default gen_random_uuid(), name text not null, headline text, intro text, short_bio text, long_bio text, career_interests text, location text, availability text, contact_email text, cta_text text, contact_cta text, photo_url text, photo_alt text, photo_position text not null default '50% 50%', resume_url text, resume_title text, resume_description text, site_title text, site_description text, og_image_url text, updated_at timestamptz not null default now());
create type public.publish_status as enum ('draft','published');
create table public.projects (id uuid primary key default gen_random_uuid(), title text not null, slug text not null unique check(slug~'^[a-z0-9]+(?:-[a-z0-9]+)*$'), category text, summary text, description text, role text, organization text, date_label text, cover_url text, cover_alt text, video_url text, external_url text, document_url text, tags text[] not null default '{}', content_blocks jsonb not null default '[]' check(jsonb_typeof(content_blocks)='array'), featured boolean not null default false, status public.publish_status not null default 'draft', display_order integer not null default 0, archived_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.project_media (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects on delete cascade, media_id uuid, url text not null, media_type text not null default 'image', alt_text text, caption text, display_order integer not null default 0, created_at timestamptz not null default now());
create table public.media (id uuid primary key default gen_random_uuid(), storage_path text not null unique, public_url text not null, filename text not null, mime_type text not null, size_bytes bigint not null check(size_bytes between 1 and 15728640), alt_text text, caption text, created_at timestamptz not null default now(), archived_at timestamptz);
alter table public.project_media add constraint project_media_media_fk foreign key(media_id) references public.media(id) on delete set null;
create table public.education (id uuid primary key default gen_random_uuid(), institution text not null, program text not null, status text, start_label text, end_label text, activities text, honors text, description text, display_order integer not null default 0, published boolean not null default true, archived_at timestamptz);
create table public.experience (id uuid primary key default gen_random_uuid(), organization text not null, position text not null, experience_type text not null default 'Other', start_date date, end_date date, is_current boolean not null default false, date_label text, location text, description text, highlights text[], display_order integer not null default 0, published boolean not null default false, archived_at timestamptz);
create table public.skill_groups (id uuid primary key default gen_random_uuid(), name text not null, display_order integer not null default 0, published boolean not null default false, archived_at timestamptz);
create table public.skills (id uuid primary key default gen_random_uuid(), group_id uuid not null references public.skill_groups on delete cascade, name text not null, display_order integer not null default 0, published boolean not null default true, archived_at timestamptz);
create table public.certifications (id uuid primary key default gen_random_uuid(), name text not null, issuer text, date_label text, credential_url text, document_url text, description text, display_order integer not null default 0, published boolean not null default false, archived_at timestamptz);
create table public.awards (id uuid primary key default gen_random_uuid(), name text not null, issuer text, date_label text, description text, media_url text, display_order integer not null default 0, published boolean not null default false, archived_at timestamptz);
create table public.organizations (id uuid primary key default gen_random_uuid(), name text not null, role text, date_label text, description text, display_order integer not null default 0, published boolean not null default false, archived_at timestamptz);
create table public.social_links (id uuid primary key default gen_random_uuid(), platform text not null, label text, url text not null, display_order integer not null default 0, published boolean not null default true, archived_at timestamptz);
create table public.site_sections (id uuid primary key default gen_random_uuid(), section_key text not null unique, visible boolean not null default true, display_order integer not null default 0, settings jsonb not null default '{}');

do $$ declare t text; begin foreach t in array array['site_profile','projects','project_media','media','education','experience','skill_groups','skills','certifications','awards','organizations','social_links','site_sections'] loop execute format('alter table public.%I enable row level security',t); end loop; end $$;
create policy public_profile_read on public.site_profile for select to anon,authenticated using(true);
create policy public_projects_read on public.projects for select to anon,authenticated using(status='published' and archived_at is null);
create policy public_project_media_read on public.project_media for select to anon,authenticated using(exists(select 1 from public.projects p where p.id=project_id and p.status='published' and p.archived_at is null));
create policy public_education_read on public.education for select to anon,authenticated using(published and archived_at is null);
create policy public_experience_read on public.experience for select to anon,authenticated using(published and archived_at is null);
create policy public_skill_groups_read on public.skill_groups for select to anon,authenticated using(published and archived_at is null);
create policy public_skills_read on public.skills for select to anon,authenticated using(published and archived_at is null and exists(select 1 from public.skill_groups g where g.id=group_id and g.published and g.archived_at is null));
create policy public_certifications_read on public.certifications for select to anon,authenticated using(published and archived_at is null);
create policy public_awards_read on public.awards for select to anon,authenticated using(published and archived_at is null);
create policy public_organizations_read on public.organizations for select to anon,authenticated using(published and archived_at is null);
create policy public_socials_read on public.social_links for select to anon,authenticated using(published and archived_at is null);
create policy public_sections_read on public.site_sections for select to anon,authenticated using(visible);
insert into public.site_profile(name,site_title,site_description) values('Patricia Camille S. Morales','Patricia Camille S. Morales','Portfolio of Patricia Camille S. Morales.');
insert into public.education(institution,program,status,published) values('Olivarez College','Bachelor of Arts in Communication','College Undergraduate',true);
insert into public.site_sections(section_key,visible,display_order) values('about',true,10),('projects',true,20),('experience',true,30),('education',true,40),('skills',true,50),('certifications',true,60),('awards',true,70),('contact',true,80);

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('portfolio-media','portfolio-media',true,15728640,array['image/jpeg','image/png','image/webp','image/avif','application/pdf','video/mp4']) on conflict(id) do update set public=excluded.public,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
create policy media_public_read on storage.objects for select to public using(bucket_id='portfolio-media');
